services:
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: cand_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: cand123@

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cand_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: cand123@