spring.application.name=backend


# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5434/cand_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=cand123@


# POSTGRESQL DB + DATA JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SECURITY
jwt.secret=change_this_secret_key_in_production
jwt.expiration=604800000

# MAIL
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test

# SWAGGER UI
springdoc.swagger-ui.path=/docs